/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenCvCanny_OpenCVCannyLib */

#ifndef _Included_OpenCvCanny_OpenCVCannyLib
#define _Included_OpenCvCanny_OpenCVCannyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenCvCanny_OpenCVCannyLib
 * Method:    cannyLauncher
 * Signature: ([I[IIILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_OpenCvCanny_OpenCVCannyLib_cannyLauncher
  (JNIEnv *, jclass, jintArray, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif


/*
这个文件的生成：
把其他没用的东西注释掉 只留jni相关的函数
先用javac将这个文件编译成.
退到jni的上一个文件夹目录
使用如下命令
javah -jni OpenCvCanny.OpenCVCannyLib
           包（文件夹）.类名（完整包名）

就可以得到整个文件 里面基本要用的信息都有了

*/